import type { Metadata, Viewport } from "next";
import { cache } from "react";
import { Marcellus, Jost, Pinyon_Script } from "next/font/google";
import { getMergedConfig } from "@/lib/settingsService";
import { getAppOrigin } from "@/lib/appUrl";
import ServiceWorkerRegister from "@/components/ServiceWorkerRegister";
import ThemeStyle from "@/components/ThemeStyle";
import { WeddingConfigProvider } from "@/components/WeddingConfigProvider";
import { LanguageProvider } from "@/components/LanguageProvider";
import "./globals.css";

// Engraved-invitation roman for headings (distinctive, not the Cormorant/Playfair reflex)
const serif = Marcellus({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-serif",
  display: "swap"
});

const sans = Jost({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-sans",
  display: "swap"
});

// Delicate formal calligraphy for the couple's name
const script = Pinyon_Script({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-script",
  display: "swap"
});

// Base URL for absolute OG/Twitter image links. Resolves NEXT_PUBLIC_SITE_URL
// (set in Vercel to your real domain) so social previews resolve correctly.
const siteUrl = getAppOrigin();

// De-dupe the settings read: generateMetadata, generateViewport, and the layout
// all call this within one request, but the DB is hit at most once.
const getConfig = cache(getMergedConfig);

export async function generateMetadata(): Promise<Metadata> {
  // Pull the live (DB-overridden) config so admin edits to the site name /
  // description show up in the browser tab and social previews.
  const config = await getConfig();
  const { siteName, description } = config.meta;
  const { combined } = config.couple;
  return {
    metadataBase: new URL(siteUrl),
    title: siteName,
    description,
    manifest: "/manifest.json",
    applicationName: combined,
    appleWebApp: {
      capable: true,
      statusBarStyle: "default",
      title: combined
    },
    openGraph: {
      title: siteName,
      description,
      siteName: combined,
      locale: "en_US",
      type: "website"
    },
    twitter: {
      card: "summary_large_image",
      title: siteName,
      description
    },
    icons: {
      icon: "/icons/icon.svg",
      // PNG generated by app/apple-icon.tsx (iOS ignores SVG apple-touch-icons)
      apple: "/apple-icon"
    },
    // Private wedding: keep the whole site out of search results.
    robots: {
      index: false,
      follow: false,
      nocache: true,
      googleBot: {
        index: false,
        follow: false
      }
    }
  };
}

export async function generateViewport(): Promise<Viewport> {
  const config = await getConfig();
  return {
    themeColor: config.meta.themeColor,
    width: "device-width",
    initialScale: 1,
    maximumScale: 5,
    viewportFit: "cover"
  };
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  // Resolve the live (DB-overridden) config on the server so every page renders
  // with the admin's edits, with no hydration mismatch.
  const config = await getConfig();

  return (
    <html lang="en" className={`${serif.variable} ${sans.variable} ${script.variable}`}>
      <head>
        <ThemeStyle theme={config.theme} />
      </head>
      <body>
        <LanguageProvider>
          <WeddingConfigProvider value={config}>{children}</WeddingConfigProvider>
        </LanguageProvider>
        <ServiceWorkerRegister />
      </body>
    </html>
  );
}
